[pytest]
pythonpath = .
testpaths = tests
markers = e2e: mark a test as an end-to-end test.
addopts = 
    -ra -q
    #--cov=.
    #--cov-report=term-missing
filterwarnings =
    ignore::PendingDeprecationWarning