"""update event outbox

Revision ID: 8250c632bbdd
Revises: e200614098db
Create Date: 2026-02-27 04:33:43.140747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8250c632bbdd'
down_revision: Union[str, Sequence[str], None] = 'e200614098db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_outbox', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('event_outbox', sa.Column('partition_key', sa.String(length=100), nullable=True))
    op.add_column('event_outbox', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_event_outbox_correlation_id'), 'event_outbox', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_partition_key'), 'event_outbox', ['partition_key'], unique=False)
    op.alter_column('health_telemetry', 'heart_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'spo2',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'body_temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.create_index('ix_notification_dispatch_scan', 'notifications', ['status', 'next_retry_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_language'), 'notifications', ['language'], unique=False)
    op.create_index(op.f('ix_notifications_next_retry_at'), 'notifications', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.drop_index(op.f('ix_user_email_deleted'), table_name='users')
    op.create_index(op.f('ix_users_deletion_requested_at'), 'users', ['deletion_requested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deletion_requested_at'), table_name='users')
    op.create_index(op.f('ix_user_email_deleted'), 'users', ['email', 'is_deleted'], unique=False)
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_next_retry_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_language'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index('ix_notification_dispatch_scan', table_name='notifications')
    op.alter_column('health_telemetry', 'body_temperature',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'spo2',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'heart_rate',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_event_outbox_partition_key'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_correlation_id'), table_name='event_outbox')
    op.drop_column('event_outbox', 'correlation_id')
    op.drop_column('event_outbox', 'partition_key')
    op.drop_column('event_outbox', 'event_type')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
