"""initial_schema

Revision ID: 99265dcacbdd
Revises: 
Create Date: 2026-02-25 11:55:41.527019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2.types

# revision identifiers, used by Alembic.
revision: str = '99265dcacbdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('processing', sa.Boolean(), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('(is_published = FALSE) OR (published_at IS NOT NULL)', name='ck_outbox_published_timestamp_required'),
    sa.CheckConstraint('(processing = FALSE) OR (locked_at IS NOT NULL)', name='ck_outbox_processing_requires_lock'),
    sa.CheckConstraint('retry_count >= 0', name='ck_outbox_retry_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_created_at'), 'event_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_is_published'), 'event_outbox', ['is_published'], unique=False)
    op.create_index(op.f('ix_event_outbox_next_retry_at'), 'event_outbox', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_processing'), 'event_outbox', ['processing'], unique=False)
    op.create_index(op.f('ix_event_outbox_topic'), 'event_outbox', ['topic'], unique=False)
    op.create_index(op.f('ix_event_outbox_updated_at'), 'event_outbox', ['updated_at'], unique=False)
    op.create_index('ix_outbox_retry_priority', 'event_outbox', ['retry_count', 'created_at'], unique=False)
    op.create_index('ix_outbox_worker_scan', 'event_outbox', ['is_published', 'processing', 'next_retry_at', 'created_at'], unique=False, postgresql_where=sa.text('is_published = FALSE AND processing = FALSE'))
    op.create_index('uq_outbox_idempotency_key', 'event_outbox', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('iot_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.Enum('WRISTBAND', 'NODE', 'GATEWAY', name='device_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DECOMMISSIONED', 'MAINTENANCE', 'LOST', name='device_status_enum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('battery_percentage', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('low_battery_alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(decommissioned_at IS NULL) OR (status != 'ACTIVE')", name='ck_device_no_active_if_decommissioned'),
    sa.CheckConstraint("\n            (status != 'DECOMMISSIONED')\n            OR (decommissioned_at IS NOT NULL)\n            ", name='ck_device_decommission_requires_timestamp'),
    sa.CheckConstraint("\n            (status != 'SUSPENDED')\n            OR (suspended_at IS NOT NULL)\n            ", name='ck_device_suspended_requires_timestamp'),
    sa.CheckConstraint("last_seen IS NULL OR last_seen <= NOW() + INTERVAL '5 minutes'", name='ck_device_no_future_heartbeat'),
    sa.CheckConstraint('battery_percentage IS NULL OR battery_percentage BETWEEN 0 AND 100', name='ck_device_battery_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_active_lookup', 'iot_devices', ['status'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index('ix_device_last_seen_status', 'iot_devices', ['last_seen', 'status'], unique=False)
    op.create_index('ix_device_low_battery_scan', 'iot_devices', ['battery_percentage'], unique=False, postgresql_where=sa.text('battery_percentage IS NOT NULL AND battery_percentage < 20'))
    op.create_index('ix_device_type_status', 'iot_devices', ['device_type', 'status'], unique=False)
    op.create_index(op.f('ix_iot_devices_api_key_hash'), 'iot_devices', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_iot_devices_battery_updated_at'), 'iot_devices', ['battery_updated_at'], unique=False)
    op.create_index(op.f('ix_iot_devices_created_at'), 'iot_devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_iot_devices_decommissioned_at'), 'iot_devices', ['decommissioned_at'], unique=False)
    op.create_index(op.f('ix_iot_devices_deleted_at'), 'iot_devices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_iot_devices_device_id'), 'iot_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_iot_devices_device_type'), 'iot_devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_iot_devices_is_deleted'), 'iot_devices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_iot_devices_is_verified'), 'iot_devices', ['is_verified'], unique=False)
    op.create_index(op.f('ix_iot_devices_last_seen'), 'iot_devices', ['last_seen'], unique=False)
    op.create_index(op.f('ix_iot_devices_low_battery_alerted_at'), 'iot_devices', ['low_battery_alerted_at'], unique=False)
    op.create_index(op.f('ix_iot_devices_status'), 'iot_devices', ['status'], unique=False)
    op.create_index(op.f('ix_iot_devices_suspended_at'), 'iot_devices', ['suspended_at'], unique=False)
    op.create_index(op.f('ix_iot_devices_updated_at'), 'iot_devices', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('TOURIST', 'AUTHORITY', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('medical_conditions', sa.String(length=500), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('is_pending_deletion', sa.Boolean(), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("last_login IS NULL OR last_login <= NOW() + INTERVAL '5 minutes'", name='ck_user_no_future_login'),
    sa.CheckConstraint("password_changed_at IS NULL OR password_changed_at <= NOW() + INTERVAL '5 minutes'", name='ck_user_no_future_password_change'),
    sa.CheckConstraint("position('@' in email) > 1", name='ck_user_email_format'),
    sa.CheckConstraint('(is_deleted = FALSE AND deleted_at IS NULL) OR (is_deleted = TRUE AND deleted_at IS NOT NULL)', name='ck_user_soft_delete_consistency'),
    sa.CheckConstraint('(is_pending_deletion = FALSE AND deletion_requested_at IS NULL) OR (is_pending_deletion = TRUE AND deletion_requested_at IS NOT NULL)', name='ck_user_deletion_workflow_consistency'),
    sa.CheckConstraint('email = lower(email)', name='ck_user_email_lowercase'),
    sa.CheckConstraint('length(password_hash) >= 20', name='ck_user_password_min_length'),
    sa.CheckConstraint('token_version >= 0', name='ck_user_token_version_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_active_role', 'users', ['role'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index('ix_user_email_deleted', 'users', ['email', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_pending_deletion'), 'users', ['is_pending_deletion'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index('uq_user_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index('uq_user_phone_active', 'users', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL AND is_deleted = FALSE'))
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_deleted = FALSE AND deleted_at IS NULL) OR (is_deleted = TRUE AND deleted_at IS NOT NULL)', name='ck_zone_soft_delete_consistency'),
    sa.CheckConstraint('NOT ST_IsEmpty(geometry)', name='ck_zone_geometry_not_empty'),
    sa.CheckConstraint('ST_IsValid(geometry)', name='ck_zone_geometry_valid'),
    sa.CheckConstraint('ST_SRID(geometry) = 4326', name='ck_zone_geometry_srid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zone_active_lookup', 'zones', ['is_active'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index('ix_zone_geometry_gist', 'zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_zone_type_active', 'zones', ['zone_type'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index(op.f('ix_zones_created_at'), 'zones', ['created_at'], unique=False)
    op.create_index(op.f('ix_zones_deleted_at'), 'zones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zones_is_deleted'), 'zones', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_zones_updated_at'), 'zones', ['updated_at'], unique=False)
    op.create_index('uq_zone_name_active', 'zones', [sa.literal_column('LOWER(name)')], unique=True, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('REGISTER_USER', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'TOKEN_REFRESH', 'PASSWORD_CHANGED', 'UPDATE_PROFILE', 'REQUEST_ACCOUNT_DELETION', 'DELETE_ACCOUNT', 'CREATE_USER', 'CREATE_INCIDENT', 'UPDATE_INCIDENT_STATUS', 'ASSIGN_INCIDENT', 'REASSIGN_INCIDENT', 'UNASSIGN_INCIDENT', 'UPDATE_DEVICE_STATUS', 'UPDATE_LOCATION', 'HEALTH_ALERT_TRIGGERED', 'CREATE_ZONE', 'UPDATE_ZONE', 'UPLOAD_MEDIA', 'DELETE_MEDIA', 'CREATE_NOTIFICATION', 'ACCESS_DENIED', 'SYSTEM_MAINTENANCE', 'OUTBOX_PUBLISHED', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.Enum('USER', 'INCIDENT', 'INCIDENT_STATUS_HISTORY', 'ZONE', 'ZONE_STATUS', 'ZONE_RISK_HISTORY', 'DEVICE', 'DEVICE_ASSIGNMENT', 'HEALTH_TELEMETRY', 'LOCATION', 'LOCATION_EVENT', 'NOTIFICATION', 'MEDIA', 'OUTBOX_EVENT', 'SYSTEM', name='audit_entity_enum'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_correlation_time', 'audit_logs', ['correlation_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity_lookup', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_updated_at'), 'audit_logs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('device_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('unassigned_at IS NULL OR unassigned_at >= assigned_at', name='ck_device_assignment_time_order'),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.device_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_assignment_device_active', 'device_assignments', ['device_id', 'unassigned_at'], unique=False)
    op.create_index('ix_device_assignment_tourist_history', 'device_assignments', ['tourist_id', 'assigned_at'], unique=False)
    op.create_index(op.f('ix_device_assignments_assigned_at'), 'device_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_device_assignments_created_at'), 'device_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_assignments_device_id'), 'device_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_assignments_tourist_id'), 'device_assignments', ['tourist_id'], unique=False)
    op.create_index(op.f('ix_device_assignments_unassigned_at'), 'device_assignments', ['unassigned_at'], unique=False)
    op.create_index(op.f('ix_device_assignments_updated_at'), 'device_assignments', ['updated_at'], unique=False)
    op.create_index('uq_device_assignment_active_device', 'device_assignments', ['device_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_table('health_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('heart_rate', sa.Float(precision=4), nullable=True),
    sa.Column('spo2', sa.Float(precision=3), nullable=True),
    sa.Column('body_temperature', sa.Float(precision=4), nullable=True),
    sa.Column('is_alert', sa.Boolean(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("recorded_at <= (NOW() + INTERVAL '5 minutes')", name='ck_health_no_far_future_records'),
    sa.CheckConstraint('(heart_rate IS NOT NULL OR spo2 IS NOT NULL OR body_temperature IS NOT NULL)', name='ck_health_at_least_one_metric'),
    sa.CheckConstraint('body_temperature IS NULL OR body_temperature BETWEEN 30 AND 45', name='ck_health_temp_realistic_range'),
    sa.CheckConstraint('heart_rate IS NULL OR heart_rate BETWEEN 20 AND 250', name='ck_health_heart_rate_realistic_range'),
    sa.CheckConstraint('spo2 IS NULL OR spo2 BETWEEN 50 AND 100', name='ck_health_spo2_realistic_range'),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.device_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_alert_lookup', 'health_telemetry', ['tourist_id', 'is_alert', 'recorded_at'], unique=False)
    op.create_index('ix_health_critical_alerts', 'health_telemetry', ['recorded_at'], unique=False, postgresql_where=sa.text('is_alert = TRUE'))
    op.create_index('ix_health_spatial', 'health_telemetry', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_health_telemetry_alert_type'), 'health_telemetry', ['alert_type'], unique=False)
    op.create_index(op.f('ix_health_telemetry_device_id'), 'health_telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_health_telemetry_is_alert'), 'health_telemetry', ['is_alert'], unique=False)
    op.create_index(op.f('ix_health_telemetry_recorded_at'), 'health_telemetry', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_health_telemetry_tourist_id'), 'health_telemetry', ['tourist_id'], unique=False)
    op.create_index('ix_health_tourist_time', 'health_telemetry', ['tourist_id', 'recorded_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'ESCALATED', 'RESOLVED', 'CLOSED', 'CANCELLED', 'REJECTED', name='incident_status_enum'), nullable=False),
    sa.Column('source', sa.Enum('MOBILE', 'IOT', 'SYSTEM', 'ML', 'HEALTH', name='incident_source_enum'), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (status IN ('RESOLVED', 'CLOSED'))\n            OR (resolved_at IS NULL)\n            ", name='ck_incident_resolution_only_when_resolved'),
    sa.CheckConstraint("\n            (status NOT IN ('RESOLVED', 'CLOSED'))\n            OR (resolved_at IS NOT NULL)\n            ", name='ck_incident_resolution_required'),
    sa.CheckConstraint("resolved_at IS NULL OR resolved_at <= NOW() + INTERVAL '5 minutes'", name='ck_incident_no_future_resolution'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_spatial', 'incidents', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_incident_status_created', 'incidents', ['status', 'created_at'], unique=False)
    op.create_index('ix_incident_tourist_active', 'incidents', ['tourist_id', 'status'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index('ix_incident_zone_active', 'incidents', ['zone_id', 'status'], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_deleted_at'), 'incidents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_incidents_is_auto_generated'), 'incidents', ['is_auto_generated'], unique=False)
    op.create_index(op.f('ix_incidents_is_deleted'), 'incidents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incidents_resolved_at'), 'incidents', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_incidents_source'), 'incidents', ['source'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_tourist_id'), 'incidents', ['tourist_id'], unique=False)
    op.create_index(op.f('ix_incidents_updated_at'), 'incidents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_incidents_zone_id'), 'incidents', ['zone_id'], unique=False)
    op.create_table('location_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('MOBILE', 'IOT', 'NODE', 'SYSTEM', name='location_event_source_enum'), nullable=False),
    sa.Column('sos_flag', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("timestamp <= NOW() + INTERVAL '5 minutes'", name='ck_location_event_no_future'),
    sa.CheckConstraint('(tourist_id IS NOT NULL OR device_id IS NOT NULL)', name='ck_location_event_identity_required'),
    sa.CheckConstraint('rssi IS NULL OR rssi BETWEEN -150 AND 0', name='ck_location_event_rssi_range'),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.device_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_device_time', 'location_events', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_location_events_device_id'), 'location_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_location_events_sos_flag'), 'location_events', ['sos_flag'], unique=False)
    op.create_index(op.f('ix_location_events_source'), 'location_events', ['source'], unique=False)
    op.create_index(op.f('ix_location_events_timestamp'), 'location_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_location_events_tourist_id'), 'location_events', ['tourist_id'], unique=False)
    op.create_index(op.f('ix_location_events_zone_id'), 'location_events', ['zone_id'], unique=False)
    op.create_index('ix_location_sos_priority', 'location_events', ['timestamp'], unique=False, postgresql_where=sa.text('sos_flag = TRUE'))
    op.create_index('ix_location_spatial', 'location_events', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_location_tourist_time', 'location_events', ['tourist_id', 'timestamp'], unique=False)
    op.create_index('ix_location_zone_sos_time', 'location_events', ['zone_id', 'sos_flag', 'timestamp'], unique=False)
    op.create_index('ix_location_zone_time', 'location_events', ['zone_id', 'timestamp'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('battery_percentage', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("updated_at <= NOW() + INTERVAL '5 minutes'", name='ck_location_no_future_update'),
    sa.CheckConstraint('\n            ST_Y(coordinates::geometry) BETWEEN -90 AND 90\n            AND\n            ST_X(coordinates::geometry) BETWEEN -180 AND 180\n            ', name='ck_location_valid_coordinates'),
    sa.CheckConstraint('accuracy_meters IS NULL OR accuracy_meters >= 0', name='ck_location_accuracy_positive'),
    sa.CheckConstraint('battery_percentage IS NULL OR battery_percentage BETWEEN 0 AND 100', name='ck_location_battery_range'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_freshness', 'locations', ['updated_at'], unique=False)
    op.create_index('ix_locations_coordinates_gist', 'locations', ['coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_locations_tourist_id'), 'locations', ['tourist_id'], unique=True)
    op.create_index(op.f('ix_locations_updated_at'), 'locations', ['updated_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'PUSH', 'SMS', name='notification_channel_enum'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notification_severity_enum'), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("sent_at IS NULL OR sent_at <= NOW() + INTERVAL '5 minutes'", name='ck_notification_no_future_sent'),
    sa.CheckConstraint('(is_read = FALSE) OR (is_sent = TRUE)', name='ck_notification_read_requires_sent'),
    sa.CheckConstraint('(is_sent = FALSE) OR (sent_at IS NOT NULL)', name='ck_notification_sent_requires_timestamp'),
    sa.CheckConstraint('(is_sent = TRUE) OR (sent_at IS NULL)', name='ck_notification_no_timestamp_if_not_sent'),
    sa.CheckConstraint('\n            (related_entity_type IS NULL AND related_entity_id IS NULL)\n            OR\n            (related_entity_type IS NOT NULL AND related_entity_id IS NOT NULL)\n            ', name='ck_notification_entity_integrity'),
    sa.CheckConstraint('retry_count >= 0 AND retry_count <= 10', name='ck_notification_retry_limit'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_dispatch_batch', 'notifications', ['is_sent', 'retry_count', 'created_at'], unique=False)
    op.create_index('ix_notification_entity_lookup', 'notifications', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_index('ix_notification_high_severity', 'notifications', ['severity', 'created_at'], unique=False, postgresql_where=sa.text("severity = 'CRITICAL'"))
    op.create_index('ix_notification_user_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('is_read = FALSE'))
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_correlation_id'), 'notifications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_idempotency_key'), 'notifications', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_is_sent'), 'notifications', ['is_sent'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_id'), 'notifications', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_entity_type'), 'notifications', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_severity'), 'notifications', ['severity'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('(is_revoked = FALSE AND revoked_at IS NULL) OR (is_revoked = TRUE AND revoked_at IS NOT NULL)', name='refresh_revocation_consistency'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'jti', name='uq_refresh_user_jti')
    )
    op.create_index('ix_refresh_token_expiry', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_token_user_active', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('is_revoked = FALSE'))
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_updated_at'), 'refresh_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('zone_risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level_enum'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), server_default=sa.text("'ml'"), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("\n            (risk_level = 'LOW' AND risk_score < 0.4)\n            OR\n            (risk_level = 'MEDIUM' AND risk_score >= 0.4 AND risk_score < 0.7)\n            OR\n            (risk_level = 'HIGH' AND risk_score >= 0.7)\n            ", name='ck_zone_risk_level_consistency'),
    sa.CheckConstraint("recorded_at <= NOW() + INTERVAL '5 minutes'", name='ck_zone_risk_no_future_records'),
    sa.CheckConstraint("source IN ('ml', 'manual', 'system')", name='ck_zone_risk_source_check'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_zone_risk_score_range'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zone_risk_history_brin_time', 'zone_risk_history', ['recorded_at'], unique=False, postgresql_using='brin')
    op.create_index(op.f('ix_zone_risk_history_correlation_id'), 'zone_risk_history', ['correlation_id'], unique=False)
    op.create_index('ix_zone_risk_history_high_risk', 'zone_risk_history', ['zone_id', 'recorded_at'], unique=False, postgresql_where=sa.text("risk_level = 'HIGH'"))
    op.create_index('ix_zone_risk_history_model_version', 'zone_risk_history', ['model_version', 'recorded_at'], unique=False)
    op.create_index('ix_zone_risk_history_zone_time', 'zone_risk_history', ['zone_id', 'recorded_at'], unique=False)
    op.create_table('zone_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level_enum'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), server_default=sa.text("'ml'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("\n            (risk_level = 'LOW' AND risk_score < 0.4)\n            OR\n            (risk_level = 'MEDIUM' AND risk_score >= 0.4 AND risk_score < 0.7)\n            OR\n            (risk_level = 'HIGH' AND risk_score >= 0.7)\n            ", name='ck_zone_status_level_consistency'),
    sa.CheckConstraint("source IN ('ml', 'manual', 'system')", name='ck_zone_status_source_check'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_zone_status_score_range'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', name='uq_zone_status_zone_id')
    )
    op.create_index(op.f('ix_zone_status_created_at'), 'zone_status', ['created_at'], unique=False)
    op.create_index('ix_zone_status_high_risk', 'zone_status', ['zone_id'], unique=False, postgresql_where=sa.text("risk_level = 'HIGH'"))
    op.create_index('ix_zone_status_model_version', 'zone_status', ['model_version'], unique=False)
    op.create_index('ix_zone_status_risk_level', 'zone_status', ['risk_level'], unique=False)
    op.create_index(op.f('ix_zone_status_updated_at'), 'zone_status', ['updated_at'], unique=False)
    op.create_table('incident_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('(unassigned_at IS NOT NULL) OR (authority_id IS NOT NULL)', name='ck_incident_assignment_active_requires_authority'),
    sa.CheckConstraint('unassigned_at IS NULL OR unassigned_at >= assigned_at', name='ck_incident_assignment_time_order'),
    sa.ForeignKeyConstraint(['authority_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authority_active_assignments', 'incident_assignments', ['authority_id', 'unassigned_at'], unique=False)
    op.create_index('ix_incident_assignment_lookup', 'incident_assignments', ['incident_id', 'unassigned_at'], unique=False)
    op.create_index(op.f('ix_incident_assignments_assigned_at'), 'incident_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_incident_assignments_authority_id'), 'incident_assignments', ['authority_id'], unique=False)
    op.create_index(op.f('ix_incident_assignments_created_at'), 'incident_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_assignments_incident_id'), 'incident_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_assignments_unassigned_at'), 'incident_assignments', ['unassigned_at'], unique=False)
    op.create_index(op.f('ix_incident_assignments_updated_at'), 'incident_assignments', ['updated_at'], unique=False)
    op.create_index('uq_incident_assignment_active', 'incident_assignments', ['incident_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_table('incident_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Enum('OPEN', 'IN_PROGRESS', 'ESCALATED', 'RESOLVED', 'CLOSED', 'CANCELLED', 'REJECTED', name='incident_status_enum'), nullable=False),
    sa.Column('new_status', sa.Enum('OPEN', 'IN_PROGRESS', 'ESCALATED', 'RESOLVED', 'CLOSED', 'CANCELLED', 'REJECTED', name='incident_status_enum'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("NOT (old_status = 'CLOSED' AND new_status = 'OPEN')", name='ck_incident_history_invalid_reopen'),
    sa.CheckConstraint("changed_at <= (NOW() + INTERVAL '5 minutes')", name='ck_incident_history_no_far_future'),
    sa.CheckConstraint('old_status <> new_status', name='ck_incident_history_no_same_transition'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_status_history_changed_at'), 'incident_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_incident_status_history_changed_by'), 'incident_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_incident_status_history_incident_id'), 'incident_status_history', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_status_history_new_status'), 'incident_status_history', ['new_status'], unique=False)
    op.create_index('ix_incident_status_sla', 'incident_status_history', ['incident_id', 'new_status', 'changed_at'], unique=False)
    op.create_index('ix_incident_status_timeline', 'incident_status_history', ['incident_id', 'changed_at'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.Enum('PROFILE_PHOTO', 'INCIDENT_RESOLUTION_PHOTO', 'INCIDENT_RESOLUTION_VIDEO', 'INCIDENT_EVIDENCE_PHOTO', 'INCIDENT_EVIDENCE_VIDEO', name='media_type_enum'), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("content_type IN ('image/jpeg', 'image/png', 'video/mp4')", name='ck_media_content_type_check'),
    sa.CheckConstraint("uploaded_at <= NOW() + INTERVAL '5 minutes'", name='ck_media_no_future_upload'),
    sa.CheckConstraint('\n            (user_id IS NOT NULL AND incident_id IS NULL)\n            OR\n            (user_id IS NULL AND incident_id IS NOT NULL)\n            ', name='ck_media_exactly_one_owner'),
    sa.CheckConstraint('file_size_bytes <= 52428800', name='ck_media_max_file_size'),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_media_file_size_positive'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index('ix_media_incident_active', 'media', ['incident_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_media_incident_id'), 'media', ['incident_id'], unique=False)
    op.create_index(op.f('ix_media_is_deleted'), 'media', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_s3_key'), 'media', ['s3_key'], unique=True)
    op.create_index(op.f('ix_media_updated_at'), 'media', ['updated_at'], unique=False)
    op.create_index(op.f('ix_media_uploaded_at'), 'media', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_media_uploaded_by'), 'media', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_index('ix_media_user_type_active', 'media', ['user_id', 'media_type', 'is_deleted'], unique=False)
    op.create_index('uq_active_profile_photo', 'media', ['user_id'], unique=True, postgresql_where=sa.text("media_type = 'PROFILE_PHOTO' AND is_deleted = FALSE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_profile_photo', table_name='media', postgresql_where=sa.text("media_type = 'PROFILE_PHOTO' AND is_deleted = FALSE"))
    op.drop_index('ix_media_user_type_active', table_name='media')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_uploaded_by'), table_name='media')
    op.drop_index(op.f('ix_media_uploaded_at'), table_name='media')
    op.drop_index(op.f('ix_media_updated_at'), table_name='media')
    op.drop_index(op.f('ix_media_s3_key'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_is_deleted'), table_name='media')
    op.drop_index(op.f('ix_media_incident_id'), table_name='media')
    op.drop_index('ix_media_incident_active', table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    op.drop_index('ix_incident_status_timeline', table_name='incident_status_history')
    op.drop_index('ix_incident_status_sla', table_name='incident_status_history')
    op.drop_index(op.f('ix_incident_status_history_new_status'), table_name='incident_status_history')
    op.drop_index(op.f('ix_incident_status_history_incident_id'), table_name='incident_status_history')
    op.drop_index(op.f('ix_incident_status_history_changed_by'), table_name='incident_status_history')
    op.drop_index(op.f('ix_incident_status_history_changed_at'), table_name='incident_status_history')
    op.drop_table('incident_status_history')
    op.drop_index('uq_incident_assignment_active', table_name='incident_assignments', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index(op.f('ix_incident_assignments_updated_at'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_unassigned_at'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_incident_id'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_created_at'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_authority_id'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_assigned_at'), table_name='incident_assignments')
    op.drop_index('ix_incident_assignment_lookup', table_name='incident_assignments')
    op.drop_index('ix_authority_active_assignments', table_name='incident_assignments')
    op.drop_table('incident_assignments')
    op.drop_index(op.f('ix_zone_status_updated_at'), table_name='zone_status')
    op.drop_index('ix_zone_status_risk_level', table_name='zone_status')
    op.drop_index('ix_zone_status_model_version', table_name='zone_status')
    op.drop_index('ix_zone_status_high_risk', table_name='zone_status', postgresql_where=sa.text("risk_level = 'HIGH'"))
    op.drop_index(op.f('ix_zone_status_created_at'), table_name='zone_status')
    op.drop_table('zone_status')
    op.drop_index('ix_zone_risk_history_zone_time', table_name='zone_risk_history')
    op.drop_index('ix_zone_risk_history_model_version', table_name='zone_risk_history')
    op.drop_index('ix_zone_risk_history_high_risk', table_name='zone_risk_history', postgresql_where=sa.text("risk_level = 'HIGH'"))
    op.drop_index(op.f('ix_zone_risk_history_correlation_id'), table_name='zone_risk_history')
    op.drop_index('ix_zone_risk_history_brin_time', table_name='zone_risk_history', postgresql_using='brin')
    op.drop_table('zone_risk_history')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_updated_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user_active', table_name='refresh_tokens', postgresql_where=sa.text('is_revoked = FALSE'))
    op.drop_index('ix_refresh_token_expiry', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_severity'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_sent'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_idempotency_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_correlation_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index('ix_notification_user_unread', table_name='notifications', postgresql_where=sa.text('is_read = FALSE'))
    op.drop_index('ix_notification_high_severity', table_name='notifications', postgresql_where=sa.text("severity = 'CRITICAL'"))
    op.drop_index('ix_notification_entity_lookup', table_name='notifications')
    op.drop_index('ix_notification_dispatch_batch', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_locations_updated_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_tourist_id'), table_name='locations')
    op.drop_index('ix_locations_coordinates_gist', table_name='locations', postgresql_using='gist')
    op.drop_index('ix_location_freshness', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_location_zone_time', table_name='location_events')
    op.drop_index('ix_location_zone_sos_time', table_name='location_events')
    op.drop_index('ix_location_tourist_time', table_name='location_events')
    op.drop_index('ix_location_spatial', table_name='location_events', postgresql_using='gist')
    op.drop_index('ix_location_sos_priority', table_name='location_events', postgresql_where=sa.text('sos_flag = TRUE'))
    op.drop_index(op.f('ix_location_events_zone_id'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_tourist_id'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_timestamp'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_source'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_sos_flag'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_device_id'), table_name='location_events')
    op.drop_index('ix_location_device_time', table_name='location_events')
    op.drop_table('location_events')
    op.drop_index(op.f('ix_incidents_zone_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_updated_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_tourist_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolved_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_deleted'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_auto_generated'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_deleted_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('ix_incident_zone_active', table_name='incidents', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_index('ix_incident_tourist_active', table_name='incidents', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_index('ix_incident_status_created', table_name='incidents')
    op.drop_index('ix_incident_spatial', table_name='incidents', postgresql_using='gist')
    op.drop_table('incidents')
    op.drop_index('ix_health_tourist_time', table_name='health_telemetry')
    op.drop_index(op.f('ix_health_telemetry_tourist_id'), table_name='health_telemetry')
    op.drop_index(op.f('ix_health_telemetry_recorded_at'), table_name='health_telemetry')
    op.drop_index(op.f('ix_health_telemetry_is_alert'), table_name='health_telemetry')
    op.drop_index(op.f('ix_health_telemetry_device_id'), table_name='health_telemetry')
    op.drop_index(op.f('ix_health_telemetry_alert_type'), table_name='health_telemetry')
    op.drop_index('ix_health_spatial', table_name='health_telemetry', postgresql_using='gist')
    op.drop_index('ix_health_critical_alerts', table_name='health_telemetry', postgresql_where=sa.text('is_alert = TRUE'))
    op.drop_index('ix_health_alert_lookup', table_name='health_telemetry')
    op.drop_table('health_telemetry')
    op.drop_index('uq_device_assignment_active_device', table_name='device_assignments', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index(op.f('ix_device_assignments_updated_at'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_unassigned_at'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_tourist_id'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_device_id'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_created_at'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_assigned_at'), table_name='device_assignments')
    op.drop_index('ix_device_assignment_tourist_history', table_name='device_assignments')
    op.drop_index('ix_device_assignment_device_active', table_name='device_assignments')
    op.drop_table('device_assignments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_updated_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity_lookup', table_name='audit_logs')
    op.drop_index('ix_audit_correlation_time', table_name='audit_logs')
    op.drop_index('ix_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_zone_name_active', table_name='zones', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_index(op.f('ix_zones_updated_at'), table_name='zones')
    op.drop_index(op.f('ix_zones_is_deleted'), table_name='zones')
    op.drop_index(op.f('ix_zones_deleted_at'), table_name='zones')
    op.drop_index(op.f('ix_zones_created_at'), table_name='zones')
    op.drop_index('ix_zone_type_active', table_name='zones', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_index('ix_zone_geometry_gist', table_name='zones', postgresql_using='gist')
    op.drop_index('ix_zone_active_lookup', table_name='zones', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_table('zones')
    op.drop_index('uq_user_phone_active', table_name='users', postgresql_where=sa.text('phone IS NOT NULL AND is_deleted = FALSE'))
    op.drop_index('uq_user_email_active', table_name='users', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_pending_deletion'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('ix_user_email_deleted', table_name='users')
    op.drop_index('ix_user_active_role', table_name='users', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_table('users')
    op.drop_index(op.f('ix_iot_devices_updated_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_suspended_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_status'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_low_battery_alerted_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_last_seen'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_is_verified'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_is_deleted'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_device_type'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_device_id'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_deleted_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_decommissioned_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_created_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_battery_updated_at'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_api_key_hash'), table_name='iot_devices')
    op.drop_index('ix_device_type_status', table_name='iot_devices')
    op.drop_index('ix_device_low_battery_scan', table_name='iot_devices', postgresql_where=sa.text('battery_percentage IS NOT NULL AND battery_percentage < 20'))
    op.drop_index('ix_device_last_seen_status', table_name='iot_devices')
    op.drop_index('ix_device_active_lookup', table_name='iot_devices', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_table('iot_devices')
    op.drop_index('uq_outbox_idempotency_key', table_name='event_outbox', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_outbox_worker_scan', table_name='event_outbox', postgresql_where=sa.text('is_published = FALSE AND processing = FALSE'))
    op.drop_index('ix_outbox_retry_priority', table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_updated_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_topic'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_processing'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_next_retry_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_is_published'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_created_at'), table_name='event_outbox')
    op.drop_table('event_outbox')
    # ### end Alembic commands ###
