"""iot_updated

Revision ID: 9c8f8cb4f488
Revises: 99265dcacbdd
Create Date: 2026-02-25 14:11:09.514256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8f8cb4f488'
down_revision: Union[str, Sequence[str], None] = '99265dcacbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_telemetry', 'heart_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'spo2',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'body_temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.alter_column('iot_devices', 'api_key_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iot_devices', 'api_key_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('health_telemetry', 'body_temperature',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'spo2',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('health_telemetry', 'heart_rate',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
